### ISSUE TITLE
Support for WMTS data

### ISSUE THREAD

**Issue by lionel68** [paul-carteron/happign#11]
Hi Paul,

I was wondering if adding support for wmts data (like https://geoservices.ign.fr/services-web-experts-economie) would be a huge hassle. terra SpatRaster object easily pile up raster layers.

Thanks again for your awesome work.

**Comment by lionel68** [comment]
Sorry, I thought that WMTS was about giving time-series raster data (like time series of population density). But apparently this is not what WMTS services are doing ...

**Comment by paul-carteron** [comment]
Hi Lionel,
Thanks for your comment.

As you find out, WMTS is not time-serie but tiled raste. This means that depending on the zoom level, it is not the same tile that is returned (more info [here](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/images-tuilees-wmts-ogc)).
I already tried to implement WMTS in happign but it's not worth it for the moment, you can have all WMTS as WMS. 

Have a nice day
