### ISSUE TITLE
Error in 'get_wfs(...)'

### ISSUE THREAD

**Issue by richaben** [paul-carteron/happign#24]
Hi Paul,

Many thanks for your work !

For several days, I've got an error with the function 'get_wfs(...)'.  This returns the following message :
```r
Error: Please check that :
- x is not empty ;
- layer is valid by running `get_layers_metadata("administratif", "wfs")`
``` 
I've got the same issue with the 'penmarch' example in the package.

Have you an idea where this comes from? (due to the ign geoplateforme service ? [cf. info here](https://geoservices.ign.fr/actualites/2024-03-redirection-url) )

> Packages version :

```
happign_0.2.2
sf_1.0-15
```

**Comment by paul-carteron** [comment]
Bonjour Benoit,

Merci pour votre retour.

Le problème vient de la bascule Geoservices vers Geoplateforme. Les nouvelles requêtes ne sont pas filtrer par catégorie (ortho, administratif,...) ce qui bloque happign.

L'IGN devrait prochainement proposer cette fonctionnalité (j'espère) et je pourrais corriger ça.

**Comment by richaben** [comment]
Bonjour Paul,

Merci pour ta réponse. Wait and see ! 😉

**Comment by paul-carteron** [comment]
Bonjour, 

Le problème a été corrigé dans le nouvelle version `happign 0.3.0`.

**Comment by richaben** [comment]
Avec un peu de retard, Merci Paul ! 👍
