### ISSUE TITLE
API Carto : erreur sur rpg

### ISSUE THREAD

**Issue by mgageo** [paul-carteron/happign#29]
Sur le script suivant
```
library(happign)
library(sf)
borders <- get_apicarto_cadastre("35051", type = "commune")
rpg <- get_apicarto_rpg(borders, annee = 2013:2021)
```
j'ai cette erreur
`Features downloaded : Erreur dans req_perform(req) : HTTP 414 URI Too Long.`

**Comment by mgageo** [comment]
Et les données pour 2022 sont disponibles depuis novembre 2023
```
Erreur dans get_apicarto_rpg(borders, annee = 2013:2022) : 
  annee must be between 2010 and 2021.
```

**Comment by mgageo** [comment]
Ainsi que 2023

**Comment by paul-carteron** [comment]
Bonjour @mgageo, 

Le problème est dû à une géométrie trop complexe. Les appels en API Carto n'ont pas de _body_ et il est obligatoire de passer par url. (https://github.com/IGNF/apicarto/issues/79). Pour cela vous pouvez utiliser le paramètre `dTolerance` qui permet de simplifier la géométrie. La fonction `get_apicarto_rpg` a été mise à jour dans le version en développement et renvoi maintenant un message d'erreur plus approprié.

```
library(happign)
#> Please make sure you have an internet connection.
#> Use happign::get_last_news() to display latest geoservice news.

borders <- get_apicarto_cadastre("35051", type = "commune")
#> Features downloaded :
#> 1

# error cause by too complex shape
rpg <- get_apicarto_rpg(borders, annee = 2013:2021)
#> Features downloaded :
#> Error in `req_perform()`:
#> ! HTTP 414 URI Too Long.

rpg <- get_apicarto_rpg(borders, annee = 2013:2021, dTolerance = 20)
#> Features downloaded : 273
#> Features downloaded : 271
#> Features downloaded : 599
#> Features downloaded : 585
#> Features downloaded : 592
#> Features downloaded : 614
#> Features downloaded : 609
#> Features downloaded : 679
#> Features downloaded : 666
#> Warning: Data before and after 2014 are different, a list is returned.
```

**Comment by paul-carteron** [comment]
Pour les données de 2022 et 2023, la fonction supporte maintenant les requêtes avec ces années mais elle ne renvoie rien. Je pense qu'il y a un problème avec les APICarto directement : https://apicarto.ign.fr/api/doc/rpg

Je vais me rapprocher de l'IGN pour en savoir plus.

**Comment by paul-carteron** [comment]
https://github.com/IGNF/apicarto/issues/113

**Comment by paul-carteron** [comment]
Résolu dans https://github.com/IGNF/apicarto/issues/113
