### ISSUE TITLE
Fonction get_isochrone introuvable

### ISSUE THREAD

**Issue by GrrdJulien** [paul-carteron/happign#31]
Bonjour,

Je découvre ce package, qui est très utile pour accéder aux web services de l'IGN depuis R. 
Cependant, en essayant le code en exemple pour [les calculs d'isochrone ou d'isodistance](https://paul-carteron.github.io/happign/reference/get_iso.html), je rencontre une erreur :

```
library(sf)
library(happign)

penmarch <- get_apicarto_cadastre("29158")
penmarch_centroid <- st_centroid(penmarch)
isochrone <- get_isochrone(penmarch_centroid, 5)
Error in get_isochrone(penmarch_centroid, 5) : 
  could not find function "get_isochrone"

```
La fonction `get_isochrone` semble introuvable, et son exécution génère une erreur.
A l'inverse, la fonction `get_apicarto_cadastre` fonctionne correctement et retourne le résultat attendu.

```
> penmarch
Simple feature collection with 1 feature and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -4.384593 ymin: 47.79558 xmax: -4.296563 ymax: 47.83044
Geodetic CRS:  WGS 84
# A tibble: 1 × 5
  id            nom_com  code_dep code_insee                                                                                geometry
  <chr>         <chr>    <chr>    <chr>                                                                           <MULTIPOLYGON [°]>
1 commune.18309 Penmarch 29       29158      (((-4.324905 47.79773, -4.325052 47.79775, -4.325106 47.79775, -4.325254 47.79776, -...

````

J'ai également essayé les fonctions get_iso et get_isodistance, mais j'obtiens une erreur similaire à get_isochrone.

J'utilise la version de happign 0.3.1 installée via CRAN  avec la version de R 4.2.2.

Merci pour votre aide et ce package,

**Comment by paul-carteron** [comment]
Bonjour Julien, 

Désolé pour le temps de réponse !

Merci pour cette remarque, le problème est réglé dans la version en développement (voir [a39f2c2](https://github.com/paul-carteron/happign/commit/a39f2c2a8a7c6b3dc51ac1a36e75fc214dc12e46).
