### ISSUE TITLE
Consider delaying connection checking

### ISSUE THREAD

**Issue by Enchufa2** [paul-carteron/happign#5]
This package checks whether there's Internet connection `.onLoad`. As a consequence, building the package fails in package repositories which do not allow Internet connection during package building. See e.g. https://copr.fedorainfracloud.org/coprs/iucar/cran/package/R-CRAN-happign/. Please, consider delaying this check or completely avoiding it when the package is being installed (not sure whether this can be detected; maybe there's some env variable you could check).

**Comment by paul-carteron** [comment]
Hi
I will completely remove the internet connection check. On the other hand, I will add a `get_last_news` function which will allow to have access to the RSS feed of geoservice.

Thanks for your comment

**Comment by Enchufa2** [comment]
Thanks! (BTW, I added an incorrect URL above, corrected now).

**Comment by paul-carteron** [comment]
Hi @Enchufa2,
I removed the connection when loading the package. I hope this will work for you.
